# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20181109_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
